name: pyping release

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: twine
      run: |
        python -m venv env
        . env/bin/activate
        python -m pip install -e .
        python -m pip install --upgrade build
        python -m pip install --upgrade twine
        python -m build
        twine upload --verbose  dist/osc_tui*whl
        twine upload --verbose  dist/osc_tui*tar.gz
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PIP_TOKEN }}
